### PR TITLE
Jshint

### LINKED ISSUE #186: .jshintrc not found
This comes up as an error from time to time when running grunt. Should this file have been included?

### PR DESCRIPTION
**Pull request by cristeahub**
Adds jshint and fixes a couple of errors caused by them.

This fixes #186 .

### CODE REVIEW

**Comment by stianjensen** [comment]
I see you've removed the undef rule. It's very nice for catching typos in variable names. As long as we declare the global variables we'll be using in globals, it should work pretty well

**Comment by cristeahub** [comment]
The old comments are here: https://github.com/ninjadev/nin/commit/dc46905bbd190bab6d09ca69e7eb84117e87a11e

**Comment by cristeahub** [comment]
I didn't enable "white", as that makes `if(condition)` not valid, and multiple people on this project uses that form of writing.

**Comment by cristeahub** [comment]
ping

**Comment by aleksanb** [comment]
Fwiw i write my control flow statements with a parentheses between the 'if' and the argument list.

**Comment by cristeahub** [comment]
> Fwiw i write my control flow statements with a parentheses between the 'if' and the argument list.

With a space?

Sigve and I have always used the from `if(condition)` for instance.

**Comment by iver56** [comment]
Whitespace checking is important. It is on by default. Without the whitespace check, mr doob style is allowed as well as sigve style :P
________________________________

**Comment by aleksanb** [comment]
Haha i meant space yes.

**Comment by cristeahub** [comment]
> Whitespace checking is important. It is on by default. Without the whitespace check, mr doob style is allowed as well as sigve style :P

Good point! I guess I'm just more used to the other style. @sigvef any input here?

**Comment by cristeahub** [comment]
Added information to the readme now.

**Comment by aleksanb** [comment]
Lgtm

**Comment by stianjensen** [comment]
Consider adding `unused` in addition to `undef` as it helps ensure variable names are written correctly, and generally cleanup unused variables

**Comment by cristeahub** [comment]
> Consider adding unused in addition to undef as it helps ensure variable names are written correctly, and generally cleanup unused variables

I purposely left them out, since we use stuff that's not declared all the time, and it would mean a lot of rewriting to change. Since that's not a smaller change I suggest we can have a either an issue where we discuss it, or just make another prq where people can discuss it. I know some of us like the freedom of this project in contrast to our other projects.

**Comment by aleksanb** [comment]
Unused is probably fine with the global thingy?
GU has to be one of the few global variables we have :)

**Comment by cristeahub** [comment]
These are the errors with unused on:
image

These are the errors with undef on:
```
Running "jshint:all" (jshint) task

Gruntfile.js
  line 4    col 3   'module' is not defined.
  line 5    col 5   'require' is not defined.
  line 6    col 5   'require' is not defined.
  line 85   col 21  'require' is not defined.

app/scripts/app.js
  line 4    col 3   'angular' is not defined.

app/scripts/controllers/bottom.js
  line 4    col 3   'angular' is not defined.
  line 31   col 30  'PROJECT' is not defined.
  line 153  col 27  'BEAN_FOR_FRAME' is not defined.
  line 154  col 37  'FRAME_FOR_BEAN' is not defined.
  line 154  col 80  'PROJECT' is not defined.

app/scripts/controllers/main.js
  line 4    col 3   'angular' is not defined.
  line 186  col 25  'clamp' is not defined.
  line 222  col 13  'Loader' is not defined.
  line 229  col 13  'CameraController' is not defined.
  line 230  col 31  'CameraController' is not defined.
  line 231  col 38  'CameraController' is not defined.
  line 253  col 13  'Loader' is not defined.
  line 264  col 13  'Loader' is not defined.

app/scripts/controllers/top.js
  line 1    col 1   'angular' is not defined.

app/scripts/directives/demo.js
  line 4    col 3   'angular' is not defined.

app/scripts/directives/dragresizable.js
  line 4    col 3   'angular' is not defined.

app/scripts/directives/keybinding.js
  line 1    col 1   'angular' is not defined.

app/scripts/directives/menubar.js
  line 4    col 3   'angular' is not defined.

app/scripts/directives/ngRightClick.js
  line 5    col 3   'angular' is not defined.

app/scripts/directives/scrollcallback.js
  line 4    col 3   'angular' is not defined.

app/scripts/directives/selectOnClick.js
  line 4    col 3   'angular' is not defined.

app/scripts/directives/waveform.js
  line 4    col 3   'angular' is not defined.
  line 12   col 27  'AudioContext' is not defined.
  line 25   col 55  'PROJECT' is not defined.
  line 31   col 32  'Waveform' is not defined.

app/scripts/services/ScriptReloader.js
  line 4    col 3   'angular' is not defined.

app/scripts/services/camera.js
  line 4    col 3   'angular' is not defined.
  line 9    col 23  'THREE' is not defined.
  line 20   col 26  'THREE' is not defined.
  line 29   col 29  'THREE' is not defined.
  line 47   col 9   'requestAnimFrame' is not defined.
  line 69   col 28  'THREE' is not defined.
  line 73   col 31  'THREE' is not defined.
  line 106  col 28  'THREE' is not defined.
  line 111  col 13  'requestAnimFrame' is not defined.
  line 143  col 16  'CameraController' is not defined.

app/scripts/services/commands.js
  line 1    col 1   'angular' is not defined.

app/scripts/services/demo.js
  line 4    col 3   'angular' is not defined.
  line 5    col 16  'bootstrap' is not defined.

app/scripts/services/render.js
  line 1    col 1   'angular' is not defined.
  line 39   col 5   'cancelTimeout' is not defined.

app/scripts/services/socket.js
  line 4    col 3   'angular' is not defined.
  line 5    col 22  'SockJS' is not defined.
```

Therefore I think we should do this in another prq, as they change stuff a lot.

**Comment by aleksanb** [comment]
Let the great linting of our time commence!

**Comment by cristeahub** [comment]
> Let the great linting of our time commence!
> 
> Edit: Most of those errors are actually errors, unused variables that don't need no binding.

These are things that hit basically the whole application, so help from everyone is needed. That is better suited in another prq in my opinion.

**Comment by sigvef** [comment]
>> Whitespace checking is important. It is on by default. Without the whitespace check, mr doob style is allowed as well as sigve style :P
> Good point! I guess I'm just more used to the other style. @sigvef any input here?

No preference, as long as the style is enforced by the linter.

**Comment by aleksanb** [comment]
Let's just go for freestyle whitespace style, as long as noone goes completely overboard.

**Comment by cristeahub** [comment]
Sounds good to me. We can make an issue for the undef/unused after this is merged and talk about if we want it there.

**Comment by stianjensen** [comment]
I just realized this .jshintrc was placed in the frontend folder, which means we still have no linting rules for the backend folder.

Moving it one folder up would make it active for both those folders, but that would also make it apply to the dasBoot folder, which is actually under the google closure compiler regime.

Food for thought.

**Comment by aleksanb** [comment]
Can't you exclude folders in .jshintrc or something?

**Comment by stianjensen** [comment]
> Can't you exclude folders in .jshintrc or something?

Mayhaps

**Pull request merged**
