### PR TITLE
Make demo music path user configurable through nin.json

### PR DESCRIPTION
**Pull request by aleksanb**
Previously, you had to have a song called music.mp3 in res, now you can
choose yourself, allowing for easy switching if needed.

### CODE REVIEW

**Comment by sigvef** [comment]
Convention vs configuration? At least keep res/music.mp3 as a default setting if music.path is unset.

**Comment by stianjensen** [comment]
It is kept as default there

**Comment by stianjensen** [comment]
But you'll need to change it more places, for instance in waveform.js in the frontend

**Comment by sigvef** [comment]
> It is kept as default there

Not if music.path is unset.

**Comment by aleksanb** [comment]
Updated to correct path in frontend too.

**Comment by sigvef** [comment]
backend/render.js also needs an update.

**Comment by aleksanb** [comment]
Okey, so it's kind of difficult to access project settings in backend right now (@stianjensen you want do do a feature exstension?) but one thing this still does is that it moves all those pesky 'res/music.mp3' to a common file!

**Comment by stianjensen** [comment]
I'll update projectSettings in backend, to make it available.

**Comment by stianjensen** [comment]
With #178 you can do
```
var musicPath = projectSettings.load(projectPath).music.path;
```

**Comment by aleksanb** [comment]
PING

**Pull request merged**
