### PR TITLE
Add shadernode

### PR DESCRIPTION
**Pull request by aleksanb**
It lives!

image

Now you can generate a ShaderNode and it will give you a Node and a Shader and it works!
The GUI will need reloading (perhaps), and you'll have to link the node up to the root node yourself.

### CODE REVIEW

**Comment by cristeahub** [comment]
Just so I'm not mistaken: the shadernode is a node that generates a plane and passes that on, right?

**Comment by stianjensen** [comment]
It renders a shader on a plane and outputs that as a texture equal to the output of most other nodes.

**Comment by stianjensen** [comment]
And you can override it to make it take other nodes as input so it functions as a post processing shader.

**Comment by cristeahub** [comment]
Ok, our old shaderlayers did a shaderpass instead of a renderpass as rendering technique. Haven't seen if there's any differences we should be aware of there, but I will in the next couple of days.

**Comment by sigvef** [comment]
You can also use it for shader-only effects, like a raymarched scene \o/

**Comment by aleksanb** [comment]
Jup!

**Comment by aleksanb** [comment]
Ooh i actually have some raymarching code lyinig around. In good style i should incorporate it into our demo!

**Comment by aleksanb** [comment]
https://github.com/aleksanb/raymarching/

**Comment by cristeahub** [comment]
> You can also use it for shader-only effects, like a raymarched scene \o/

This shadernode can be used for that, or do we need to use a shaderpass instead?

**Comment by stianjensen** [comment]
> This shadernode can be used for that, or do we need to use a shaderpass instead?

We can use this node for that.

**Pull request merged**
