### PR TITLE
Exclude Thumbs.db in compiled bin

### PR DESCRIPTION
**Pull request by iver56**

### CODE REVIEW

**Comment by sigvef** [comment]
Is there a better way to implement this? I'm not sure we want to maintain a list of things to ignore (Thumbs.db, DS_Store, etc). Can we do something else to make sure Thumbs.db and friends don't appear?

**Comment by iver56** [comment]
Use .gitignore in some way, perhaps?

**Comment by sigvef** [comment]
I like that idea much better.

**Comment by iver56** [comment]
Sure, sounds like a good idea. Would you like to do it?

**Comment by sigvef** [comment]
Ok.

**Pull request closed without merging**
