### PR TITLE
Music bar styles

### PR DESCRIPTION
**Pull request by sigvef**
This adds bpm-based lines to the music view, and some additional music
variable info panels.

image

### CODE REVIEW

**Comment by aleksanb** [comment]
image

The bars seem to be all over the place.
In addition, when you set a loop, the green bars are not placed at the same position as the other bars.
Presumably they should use the same form of bar computation.

**Comment by stianjensen** [comment]
> In addition, when you set a loop, the green bars are not placed at the same position as the other bars.
> Presumably they should use the same form of bar computation.

The bar lines are every fourth beat, while the loop point can snap to every beat, maybe?

**Comment by sigvef** [comment]
> The bars seem to be all over the place.

What do you mean?

**Comment by sigvef** [comment]
> In addition, when you set a loop, the green bars are not placed at the same position as the other bars.

The green bars are snapped to quavers (i.e., one fourth of a bar), and the lines are snapped to bars.

**Comment by sigvef** [comment]
> There seems to be a ton of logging going on:

I don't think so? Are you on the right branch?

**Comment by sigvef** [comment]
I'm changing the rendering strategy, so closing this for now.

**Pull request closed without merging**
