### PR TITLE
Visuals, yo

### PR DESCRIPTION
**Pull request by sigvef**
This pull request simplifies the Gruntfile, replaces css with less, introduces some base colors and tweaks a bunch of visuals.

image

image

---

(Here is an image of how it looks without this pull request: image)

### CODE REVIEW

**Comment by aleksanb** [comment]
#FLStudio :package:

**Comment by cristeahub** [comment]
> #FLStudio

I agree. What about making the colors more light? Like a light blue or green?

**Comment by aleksanb** [comment]
super happy fun time cat melting shampoo from the same people who brought you mister sparkle _3c15aa8ff532bc2f38ce49aeca04ba80

**Comment by sigvef** [comment]
I want FL colors.

**Comment by cristeahub** [comment]
> I want FL colors.

Let's put up a vote on the color scheme

**Comment by aleksanb** [comment]
Porque nos dos! Vi kan kjøre light- og dark theme. Vi fixer bare to lessfiler (dark.theme og light.theme) og så sier vi bare hvilken det er som skal lastes i nin configen (sammen med keysa)!

**Comment by cristeahub** [comment]
> Porque nos dos! Vi kan kjøre light- og dark theme. Vi fixer bare to lessfiler (dark.theme og light.theme) og så sier vi bare hvilken det er som skal lastes i nin configen (sammen med keysa)!

:+1:

**Comment by sigvef** [comment]
> themes
 
Yes, one of my (undeclared) motivations for moving to less and defining colors separately was to enable theming down the line.

**Comment by aleksanb** [comment]
grunt build
>> Local Npm module "grunt-contrib-less" not found. Is it installed?
Warning: Task "less:dist" not found. Use --force to continue.

Aborted due to warnings. :(

**Comment by aleksanb** [comment]
I tried adding gurnt contrib less to my package.json. got this then

Going through app/index.html to update the config
Looking for build script HTML comment blocks
Warning: Cannot find module '/home/aleksanb/Projects/solskogen/nintage/nin/frontend/node_modules/grunt-usemin/lib/config/conjat' Use --force to continue.

Aborted due to warnings.

Probably more dependencies missing?

**Comment by sigvef** [comment]
ping

**Comment by sigvef** [comment]
ping

**Comment by iver56** [comment]
nin.png is rad!

**Comment by cristeahub** [comment]
Wait? Did we agree on the design?

**Comment by aleksanb** [comment]
It was easy to take it in right now, and it was an improvement on what we used to have.
As soon as someone makes a light theme or whatever we can add an entry in the option menu that simply toggles between the two themes by changing a class in the frontend, or if more preferable, a backend custom theming option integrated with your settings module.

**Comment by cristeahub** [comment]
> It was easy to take it in right now, and it was an improvement on what we used to have.
> As soon as someone makes a light theme or whatever we can add an entry in the option menu that simply toggles between the two themes by changing a class in the frontend, or if more preferable, a backend custom theming option integrated with your settings module.

Why wasn't the alternative theme included before the merge? Usually when someone proposes a change that someone disagrees with, it will not be merged. Like for instance if someone wants to change some key bindings and someone disagrees with those bindings.

**Comment by aleksanb** [comment]
I feel the difference goes on introducing new features versus changing existing ones.
This update introduces new elements to the existing 'fl-ish' design, as opposed to going in a different direction.
With keybinds, it's easier to add new ones than to change old ones, as people might have gotten used to it.

I can revert the branch if you want?

**Comment by cristeahub** [comment]
> I feel the difference goes on introducing new features versus changing existing ones.
> This update introduces new elements to the existing 'fl-ish' design, as opposed to going in a different direction.
> With keybinds, it's easier to add new ones than to change old ones, as people might have gotten used to it.
> 
> I can revert the branch if you want?

I think this is exactly as changing old keys. The old design looked one way and people were used to it, and it was changed. I'm not sure what new features you are talking about.

I don't think reverting the branch is necessarily the right call, but I would like to clarify when it is ok to merge something when people disagrees and when not.

**Pull request merged**
