### PR TITLE
Use path.sep for cross-platform path splitting

### PR DESCRIPTION
**Pull request by stianjensen**

### CODE REVIEW

**Comment by iver56** [comment]
I'm not able to test this atm. If it works for you, go ahead and merge

**Comment by aleksanb** [comment]
I think you want to use path.parse(thepath).base instead, as documented here: https://nodejs.org/api/path.html.

**Comment by stianjensen** [comment]
> I think you want to use path.parse(thepath).base instead, as documented here: 

That won't work, since the file that is being changed has a path like this:
`src/shaders/yolo/fragment.glsl`

`base` will then be `fragment.glsl`, and `dir` will be `src/shaders/yolo`.

**Comment by aleksanb** [comment]
Right now we're only using the second segment from the shader path (pathParts[2]), wouldn't those two be equivalent then

**Comment by stianjensen** [comment]
`'src/shaders/yolo/fragment.glsl'.split('/')` equals `['src', 'shaders', 'yolo', 'fragment.glsl']`, so `[2]` will then be `yolo`, while `base` will be `fragment.glsl`.

**Comment by aleksanb** [comment]
Hm. Doesn't seem like node's path has any built-in splitting thing (and just recommends you to split yourself).

**Comment by stianjensen** [comment]
> Hm. Doesn't seem like node's path has any built-in splitting thing (and just recommends you to split yourself).

Correct:
https://github.com/nodejs/node/issues/5523

**Pull request merged**
