### PR TITLE
Add automationClip support

### PR DESCRIPTION
**Pull request by sigvef**
See #208 for previous discussion.

### CODE REVIEW

**Comment by sigvef** [comment]
ping, now has an automation clip editor UI as well.

**Comment by sigvef** [comment]
image

**Comment by sigvef** [comment]
ping

**Comment by sigvef** [comment]
ping, rebased

**Comment by aleksanb** [comment]
sadface

An undefined clipName might be the case of one? Not sure where $scope.clipName is set.
Can the error be due to using normal html height and width attributes, and not something like ng-height, ng-width?

clippu

**Comment by sigvef** [comment]
I'm closing this since it isn't all to compatible with node-based nin.

**Comment by sigvef** [comment]
s/to/too/

**Pull request closed without merging**
