### PR TITLE
Add travis.yml

### PR DESCRIPTION
**Pull request by stianjensen**
This is working now. Not the cleanest, prettiest config, but it should be working.

### CODE REVIEW

**Comment by stianjensen** [comment]
`|| true` problems:

screenshot 2016-11-13 03 25 33

**Comment by sigvef** [comment]
Hm yes I expected as much :/

**Comment by cristeahub** [comment]
What was the reason for `|| true`?

**Comment by sigvef** [comment]
It was added because `npm run lint` adds a bunch of crap to the output if the script exits with a non-zero return code. `|| true` was a hack to make sure that the linting script always exited nicely, even when there were errors.

Without the hack:

image

With the hack:

image

**Comment by cristeahub** [comment]
Ahh right! Yeah, I noticed that too. I guess we can have Travis specific instructions.

**Comment by aleksanb** [comment]
So... do we merge this?

**Comment by stianjensen** [comment]
No, it's a WIP. I will ping when I've updated.

**Comment by stianjensen** [comment]
There's still one lint error in the backend, but it's an actual error because we've stopped using layers.

**Comment by sigvef** [comment]
Can you add a quick fix for that as a second commit in this pull request? That way we won't break the build in our other outstanding pull requests if we merge this.

**Comment by stianjensen** [comment]
ping

**Pull request merged**
